### ISSUE TITLE
Text doesn't show until keyboard is closed

### ISSUE THREAD

**Issue by calvinzirk** [brightsign/html-virtual-keyboard#2]
When an input field is touched, the keyboard shows, but the caret is non-responsive.
Text only shows up in the input field after the keyboard is closed.
Also, the enter button doesn't work, as I imagine it should either close the keyboard, or advance to the next field.

**Comment by Dquinteo** [comment]
Has anyone fixed this?

**Comment by bhastings1019** [comment]
Hi @calvinzirk @Dquinteo - The example is being updated. I can confirm these keys are now responsive. If there are continued issues, please let us know. Creating a Github Issue or creating a _Support Ticket_ by emailing _support@brightsign.biz_ are both proper. Thank you.
