### ISSUE TITLE
keyboard dynamic

### ISSUE THREAD

**Issue by EduardoGante** [brightsign/html-virtual-keyboard#3]
I need the keyboard to be dynamic or mobile, that can be moved anywhere on the screen.

Is there anything that is possible?

in advance thank you for the extraordinary project

**Comment by bhastings1019** [comment]
Hi @EduardoGante - We have updated a example to outline where the keyboard's size, orientation, and location are defined and how to update these during development and testing. At the moment, this example does not support a "drag and drop" feature to move the keyboard on the screen.
